USE [Klinikum]
GO

/****** Object:  Table [dbo].[QStufen]    Script Date: 24.11.2022 06:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QStufen](
	[QStufeID] [int] IDENTITY(1,1) NOT NULL,
	[QStufe] [nvarchar](50) NOT NULL,
	[Kommentar] [nvarchar](max) NULL,
 CONSTRAINT [PK_QStufenID] PRIMARY KEY CLUSTERED 
(
	[QStufeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

